-- MySQL Script generated by MySQL Workbench
-- Wed Aug 14 22:17:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema posworld
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema posworld
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posworld` DEFAULT CHARACTER SET utf8 ;
USE `posworld` ;

-- -----------------------------------------------------
-- Table `posworld`.`UserMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`UserMaster` (
  `UM_EMP_ID` INT NOT NULL,
  `UM_EPF_NO` INT NULL,
  `UM_EMP_FIRST_NAME` VARCHAR(100) NULL,
  `UM_EMP_LAST_NAME` VARCHAR(100) NULL,
  `UM_EMP_OTHER_NAME` VARCHAR(200) NULL,
  `UM_EMP_FULL_NAME` VARCHAR(250) NULL,
  `UM_EMP_NIC_NO` VARCHAR(15) NULL,
  `UM_EMP_PP_NO` VARCHAR(15) NULL,
  `UM_EMP_EMAIL` VARCHAR(50) NULL,
  `UM_EMP_MOBILE_NO` VARCHAR(10) NULL,
  `UM_EMP_RESIDENTS_NO` VARCHAR(10) NULL,
  `UM_EMP_OTHER_NO` VARCHAR(10) NULL,
  `UM_EMP_ADDRESS` VARCHAR(250) NULL,
  `UM_EMP_PROVINCE_ID` INT NULL,
  `UM_EMP_DISTRICT_ID` INT NULL,
  `UM_EMP_CITY_ID` INT NULL,
  `UM_EMP_GENDER` VARCHAR(10) NULL,
  `UM_EMP_RELEGON` VARCHAR(20) NULL,
  `UM_EMP_RACE` VARCHAR(20) NULL,
  `UM_EMP_NATIONALITY` VARCHAR(20) NULL,
  `UM_EMP_IMAGE` VARCHAR(20) NULL,
  `UM_EMP_REMARKS` VARCHAR(250) NULL,
  `UM_EMP_LOCATION` VARCHAR(20) NULL,
  `UM_EMP_DEVISION` VARCHAR(20) NULL,
  `UM_EMP_DESIGNATION` VARCHAR(50) NULL,
  `UM_EMP_EMPLOYEE_STATUS` VARCHAR(10) NULL,
  `UM_EMP_USER_ROLE_ID` INT NULL,
  `UM_EMP_STATUS` VARCHAR(20) NULL,
  `UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `UM_EMP_PASSWORD` VARCHAR(50) NULL,
  `UM_EMP_QUECTION_1` VARCHAR(200) NULL,
  `UM_EMP_ANSWER_1` VARCHAR(250) NULL,
  `UM_EMP_QUECTION_2` VARCHAR(200) NULL,
  `UM_EMP_ANSWER_2` VARCHAR(250) NULL,
  `UserMaster_UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `UM_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`UM_EMP_USERNAME`),
  INDEX `fk_UserMaster_UserMaster1_idx` (`UserMaster_UM_EMP_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_UserMaster_UserMaster1`
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `mydb`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`ProductMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`ProductMaster` (
  `PM_ID` INT NOT NULL,
  `PM_CODE` VARCHAR(10) NULL,
  `PM_BATCH_NO` VARCHAR(10) NULL,
  `PM_NAME` VARCHAR(150) NULL,
  `PM_DISCRIPTION` VARCHAR(250) NULL,
  `PM_PURCHASE_PRICE` DOUBLE NULL,
  `PM_MANUFACTURE_DATE` DATE NULL,
  `PM_SALES_PRICE` DOUBLE NULL,
  `PM_PACKED_FATE` DATE NULL,
  `PM_SUPPLIER_ID` INT NULL,
  `PM_EXPIRY_DATE` DATE NULL,
  `PM_STATUS` VARCHAR(20) NULL,
  `PM_REMARKS` VARCHAR(250) NULL,
  `UserMaster_UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `UM_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`PM_ID`),
  INDEX `fk_ProductMaster_UserMaster1_idx` (`UserMaster_UM_EMP_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_ProductMaster_UserMaster1`
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `mydb`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`AccountMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`AccountMaster` (
  `AM_ID` INT NOT NULL,
  `AM_CODE` VARCHAR(10) NULL,
  `AM_NAME` VARCHAR(150) NULL,
  `AM_CATEGORY` VARCHAR(100) NULL,
  `AM_PARENT` VARCHAR(100) NULL,
  `AM_GROUP` VARCHAR(10) NULL,
  `AM_TYPE` VARCHAR(100) NULL,
  `AM_SIGN` VARCHAR(10) NULL,
  `AM_OPENING BALANCE` DOUBLE NULL,
  `AM_ACC_NO` VARCHAR(50) NULL,
  `AM_ACC_TYPE` VARCHAR(50) NULL,
  `AM_BANK` VARCHAR(50) NULL,
  `AM_BRANCH` VARCHAR(50) NULL,
  `AM_CONTACT` VARCHAR(50) NULL,
  `AM_PHONE_NO_1` VARCHAR(50) NULL,
  `AM_PHONE_NO_2` VARCHAR(50) NULL,
  `AM_EMAIL` VARCHAR(50) NULL,
  `AM_VAT_NO` VARCHAR(50) NULL,
  `AM_ADDRESS` VARCHAR(250) NULL,
  `AM_REMARKS` VARCHAR(250) NULL,
  PRIMARY KEY (`AM_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`DocumentsMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`DocumentsMaster` (
  `DM_ID` INT NOT NULL,
  `DM_TYPE` VARCHAR(50) NOT NULL,
  `DM_NUMBER` INT NOT NULL,
  `DM_DATE` DATE NOT NULL,
  `DM_NAME` VARCHAR(150) NULL,
  `DM_UPDATE_USER` VARCHAR(50) NOT NULL,
  `DM_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`DM_ID`),
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `posworld`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`DocumentsMaster_OLD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`DocumentsMaster_OLD` (
  `DM_ID` INT NOT NULL,
  `DM_PURCHASE_ORDER_NO` INT NULL,
  `DM_PURCHASE_ORDER_DATE` DATE NULL,
  `DM_EXPECTED_DELIVERY_DATE` DATE NULL,
  `DM_SUPPLIER_NAME` VARCHAR(150) NULL,
  `DM_PURCHASE_ORDER_NUMBER` INT NULL,
  `DM_PURCHASE_RETURN_NUMBER` INT NULL,
  `DM_PURCHASE_RETURN_DATE` DATE NULL,
  `DM_GOODS_ISSUE_NOTE_NO` INT NULL,
  `DM_GOODS_ISSUE_NOTE_DATE` DATE NULL,
  `DM_GOODS_RETURN_NOTE_NO` INT NULL,
  `DM_GOODS_RETURN_NOTE_DATE` DATE NULL,
  `DM_PRIVILAGE_CARD` VARCHAR(50) NULL,
  `DM_CUSTOMER_NAME` VARCHAR(150) NULL,
  `DM_INVOICE_NUMBER` INT NULL,
  `DM_INVOICE_DATE` DATE NULL,
  `DM_SALES_RETURN_NUMBER` INT NULL,
  `DM_SALES_RETURN_DATE` DATE NULL,
  `DM_BANK_NAME` VARCHAR(50) NULL,
  `DM_CARD_NAME` VARCHAR(50) NULL,
  `DM_CARD_TYPE` VARCHAR(50) NULL,
  `DM_CARD_NUMBER` VARCHAR(50) NULL,
  `DM_GROSS_TOTAL` DOUBLE NULL,
  `DM_TOTAL_ITEM_DISCOUNT` DOUBLE NULL,
  `DM_SPECIAL DISCOUNT` DOUBLE NULL,
  `DM_TOTAL_DISCOUNT` DOUBLE NULL,
  `DM_NET_TOTAL` DOUBLE NULL,
  `DM_PAYMENT_TYPE` DOUBLE NULL,
  `DM_CASH_RECEIVED` DOUBLE NULL,
  `DM_CASH_BALANCE` DOUBLE NULL,
  `DM_USERNAME` VARCHAR(50) NOT NULL,
  `UserMaster_UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `DM_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`DM_ID`),
  INDEX `fk_DocumentsMaster_UserMaster1_idx` (`UserMaster_UM_EMP_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_DocumentsMaster_UserMaster1`
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `mydb`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`DocumentsDetails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`DocumentsDetails` (
  `DD_ID` INT NOT NULL,
  `DD_ITEM_CODE` VARCHAR(15) NULL,
  `DD_BATCH_NO` INT NULL,
  `DD_ITEM_NAME` VARCHAR(100) NULL,
  `DD_ITEM_DESCRIPTION` VARCHAR(150) NULL,
  `DD_UNIT_PRICE` DOUBLE NULL,
  `DD_QUANTITY` DOUBLE NULL,
  `DD_PURCHASE_PRICE` DOUBLE NULL,
  `DD_MANUFACTURE_DATE` DATE NULL,
  `DD_PACKED_DATE` DATE NULL,
  `DD_EXPIRY_DATE` DATE NULL,
  `DD_DISCOUNT` DOUBLE NULL,
  `DD_SALES_PRICE` DOUBLE NULL,
  `DD_RETURN_PURPOSE` DOUBLE NULL,
  `DD_SALES_RETURN_PRICE` DOUBLE NULL,
  `DD_REMARKS` VARCHAR(250) NULL,
  `DocumentsMaster_DM_ID` INT NOT NULL,
  PRIMARY KEY (`DD_ID`),
  INDEX `fk_DocumentsDetails_DocumentsMaster_idx` (`DocumentsMaster_DM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DocumentsDetails_DocumentsMaster`
    FOREIGN KEY (`DocumentsMaster_DM_ID`)
    REFERENCES `mydb`.`DocumentsMaster` (`DM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`DocumenTypetMaster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`DocumenTypetMaster` (
  `DTM_ID` INT NOT NULL,
  `DTM_NAME` VARCHAR(50) NULL,
  PRIMARY KEY (`DTM_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`ProductTransactionStores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`ProductTransactionStores` (
  `PTS_ID` INT NOT NULL,
  `DocumentsMaster_DM_ID` INT NOT NULL,
  `ProductMaster_PM_ID` INT NOT NULL,
  `DocumenTypetMaster_DTM_ID` INT NOT NULL,
  `PTS_STOCK_ADD` DOUBLE NULL,
  `PTS_STOCK_DEDUCT` DOUBLE NULL,
  `UserMaster_UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `PTS_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`PTS_ID`),
  INDEX `fk_ProductTransactionStores_ProductMaster1_idx` (`ProductMaster_PM_ID` ASC) VISIBLE,
  INDEX `fk_ProductTransactionStores_DocumenTypetMaster1_idx` (`DocumenTypetMaster_DTM_ID` ASC) VISIBLE,
  INDEX `fk_ProductTransactionStores_UserMaster1_idx` (`UserMaster_UM_EMP_USERNAME` ASC) VISIBLE,
  INDEX `fk_ProductTransactionStores_DocumentsMaster1_idx` (`DocumentsMaster_DM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ProductTransactionStores_ProductMaster1`
    FOREIGN KEY (`ProductMaster_PM_ID`)
    REFERENCES `mydb`.`ProductMaster` (`PM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTransactionStores_DocumenTypetMaster1`
    FOREIGN KEY (`DocumenTypetMaster_DTM_ID`)
    REFERENCES `mydb`.`DocumenTypetMaster` (`DTM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTransactionStores_UserMaster1`
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `mydb`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTransactionStores_DocumentsMaster1`
    FOREIGN KEY (`DocumentsMaster_DM_ID`)
    REFERENCES `mydb`.`DocumentsMaster` (`DM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`ProductTransactionShowroom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`ProductTransactionShowroom` (
  `PTSR_ID` INT NOT NULL,
  `ProductMaster_PM_ID` INT NOT NULL,
  `DocumentsMaster_DM_ID` INT NOT NULL,
  `DocumenTypetMaster_DTM_ID` INT NOT NULL,
  `PTSR_STOCK_ADD` DOUBLE NULL,
  `PTSR_STOCK_DEDUCT` DOUBLE NULL,
  `UserMaster_UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `PTSR_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`PTSR_ID`),
  INDEX `fk_ProductTransactionShowroom_ProductMaster1_idx` (`ProductMaster_PM_ID` ASC) VISIBLE,
  INDEX `fk_ProductTransactionShowroom_DocumenTypetMaster1_idx` (`DocumenTypetMaster_DTM_ID` ASC) VISIBLE,
  INDEX `fk_ProductTransactionShowroom_UserMaster1_idx` (`UserMaster_UM_EMP_USERNAME` ASC) VISIBLE,
  INDEX `fk_ProductTransactionShowroom_DocumentsMaster1_idx` (`DocumentsMaster_DM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ProductTransactionShowroom_ProductMaster1`
    FOREIGN KEY (`ProductMaster_PM_ID`)
    REFERENCES `mydb`.`ProductMaster` (`PM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTransactionShowroom_DocumenTypetMaster1`
    FOREIGN KEY (`DocumenTypetMaster_DTM_ID`)
    REFERENCES `mydb`.`DocumenTypetMaster` (`DTM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTransactionShowroom_UserMaster1`
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `mydb`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductTransactionShowroom_DocumentsMaster1`
    FOREIGN KEY (`DocumentsMaster_DM_ID`)
    REFERENCES `mydb`.`DocumentsMaster` (`DM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posworld`.`AccountsTransaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posworld`.`AccountsTransaction` (
  `AT_ID` INT NOT NULL,
  `AT_CREDIT` DOUBLE NULL,
  `AT_DEBIT` DOUBLE NULL,
  `AccountMaster_AM_ID` INT NOT NULL,
  `DocumentsMaster_DM_ID` INT NOT NULL,
  `DocumenTypetMaster_DTM_ID` INT NOT NULL,
  `UserMaster_UM_EMP_USERNAME` VARCHAR(50) NOT NULL,
  `AT_UPDATE_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`AT_ID`),
  INDEX `fk_AccountsTransaction_AccountMaster1_idx` (`AccountMaster_AM_ID` ASC) VISIBLE,
  INDEX `fk_AccountsTransaction_DocumentsMaster1_idx` (`DocumentsMaster_DM_ID` ASC) VISIBLE,
  INDEX `fk_AccountsTransaction_DocumenTypetMaster1_idx` (`DocumenTypetMaster_DTM_ID` ASC) VISIBLE,
  INDEX `fk_AccountsTransaction_UserMaster1_idx` (`UserMaster_UM_EMP_USERNAME` ASC) VISIBLE,
  CONSTRAINT `fk_AccountsTransaction_AccountMaster1`
    FOREIGN KEY (`AccountMaster_AM_ID`)
    REFERENCES `mydb`.`AccountMaster` (`AM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccountsTransaction_DocumentsMaster1`
    FOREIGN KEY (`DocumentsMaster_DM_ID`)
    REFERENCES `mydb`.`DocumentsMaster` (`DM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccountsTransaction_DocumenTypetMaster1`
    FOREIGN KEY (`DocumenTypetMaster_DTM_ID`)
    REFERENCES `mydb`.`DocumenTypetMaster` (`DTM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AccountsTransaction_UserMaster1`
    FOREIGN KEY (`UserMaster_UM_EMP_USERNAME`)
    REFERENCES `mydb`.`UserMaster` (`UM_EMP_USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
