/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

/**
 *
 * @author MYPC
 */
public class PanelTest extends javax.swing.JPanel {

    /**
     * Creates new form PanelTest
     */
    public PanelTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lblUsername3 = new javax.swing.JLabel();
        txtOpeningBalance = new javax.swing.JTextField();
        lblPassword4 = new javax.swing.JLabel();
        lblPassword5 = new javax.swing.JLabel();
        lblUsername4 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        lblPassword6 = new javax.swing.JLabel();
        lblUsername6 = new javax.swing.JLabel();
        lblPassword7 = new javax.swing.JLabel();
        lblUsername7 = new javax.swing.JLabel();
        radioChild = new javax.swing.JRadioButton();
        radioParnt = new javax.swing.JRadioButton();
        comboCategory = new javax.swing.JComboBox();
        comboType = new javax.swing.JComboBox();
        comboParent = new javax.swing.JComboBox();
        comboSign = new javax.swing.JComboBox();
        txtAccountName1 = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        lblBank = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblVATNo = new javax.swing.JLabel();
        txtVATNo = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblAccountType = new javax.swing.JLabel();
        txtPhoneNo1 = new javax.swing.JTextField();
        lblBranch = new javax.swing.JLabel();
        lblRemarks = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        comboAccountType = new javax.swing.JComboBox();
        txtAccNo = new javax.swing.JTextField();
        lblContact1 = new javax.swing.JLabel();
        lblAccNO = new javax.swing.JLabel();
        lblPhoneNo3 = new javax.swing.JLabel();
        lblPhoneNo4 = new javax.swing.JLabel();
        txtPhoneNo2 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        comboBank = new javax.swing.JComboBox();
        comboBranch = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        btnUpdate1 = new javax.swing.JButton();
        btnReset1 = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblUsername3.setText("CODE");
        jPanel4.add(lblUsername3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtOpeningBalance.setBackground(new java.awt.Color(255, 255, 150));
        txtOpeningBalance.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel4.add(txtOpeningBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 240, 30));

        lblPassword4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPassword4.setText("CATEGORY");
        jPanel4.add(lblPassword4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        lblPassword5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPassword5.setText("PARENT");
        jPanel4.add(lblPassword5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, -1, -1));

        lblUsername4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblUsername4.setText("ACCOUNT NAME");
        jPanel4.add(lblUsername4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        txtCode.setBackground(new java.awt.Color(255, 255, 150));
        txtCode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel4.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 250, 30));

        lblPassword6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPassword6.setText("SIGN");
        jPanel4.add(lblPassword6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        lblUsername6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblUsername6.setText("GROUP");
        jPanel4.add(lblUsername6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblPassword7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPassword7.setText("OPENING BALANCE");
        jPanel4.add(lblPassword7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        lblUsername7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblUsername7.setText("TYPE");
        jPanel4.add(lblUsername7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        radioChild.setText("CHILD");
        jPanel4.add(radioChild, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        radioParnt.setText("PARENT");
        jPanel4.add(radioParnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select Category -" }));
        jPanel4.add(comboCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 240, 30));

        comboType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select Type -" }));
        jPanel4.add(comboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 240, 30));

        comboParent.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select Parent Name -" }));
        jPanel4.add(comboParent, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, 30));

        comboSign.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "- Select Sign -" }));
        jPanel4.add(comboSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 250, 30));

        txtAccountName1.setBackground(new java.awt.Color(255, 255, 150));
        txtAccountName1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel4.add(txtAccountName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 240, 30));

        jTabbedPane1.addTab("GENERAL", jPanel4);

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBank.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblBank.setText("BANK");
        panel1.add(lblBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtcontact.setBackground(new java.awt.Color(255, 255, 150));
        txtcontact.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 240, 30));

        lblEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblEmail.setText("E-MAIL");
        panel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, -1, -1));

        lblVATNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblVATNo.setText("VAT NO");
        panel1.add(lblVATNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtVATNo.setBackground(new java.awt.Color(255, 255, 150));
        txtVATNo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtVATNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVATNoActionPerformed(evt);
            }
        });
        panel1.add(txtVATNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 240, 30));

        lblAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAddress.setText("ADDRESS");
        panel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtAddress.setBackground(new java.awt.Color(255, 255, 150));
        txtAddress.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 650, 30));

        lblAccountType.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAccountType.setText("ACCOUNT TYPE");
        panel1.add(lblAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        txtPhoneNo1.setBackground(new java.awt.Color(255, 255, 150));
        txtPhoneNo1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panel1.add(txtPhoneNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 250, 30));

        lblBranch.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblBranch.setText("BRANCH");
        panel1.add(lblBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        lblRemarks.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblRemarks.setText("REMARKS");
        panel1.add(lblRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        txtRemarks.setBackground(new java.awt.Color(255, 255, 150));
        txtRemarks.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtRemarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRemarksActionPerformed(evt);
            }
        });
        panel1.add(txtRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 250, 30));

        comboAccountType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel1.add(comboAccountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 250, 30));
        panel1.add(txtAccNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 240, 30));

        lblContact1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblContact1.setText("CONTACT");
        panel1.add(lblContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblAccNO.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblAccNO.setText("ACC.NO");
        panel1.add(lblAccNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblPhoneNo3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPhoneNo3.setText("PHONE NO - 1");
        panel1.add(lblPhoneNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        lblPhoneNo4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPhoneNo4.setText("PHONE NO - 2");
        panel1.add(lblPhoneNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        txtPhoneNo2.setBackground(new java.awt.Color(255, 255, 150));
        txtPhoneNo2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panel1.add(txtPhoneNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 250, 30));

        txtEmail.setBackground(new java.awt.Color(255, 255, 150));
        txtEmail.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        panel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 240, 30));

        comboBank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel1.add(comboBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 240, 30));

        comboBranch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panel1.add(comboBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 250, 30));

        jTabbedPane1.addTab("DETAILS", panel1);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 290));

        btnUpdate1.setBackground(new java.awt.Color(155, 194, 230));
        btnUpdate1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnUpdate1.setText("UPDATE");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });

        btnReset1.setBackground(new java.awt.Color(155, 194, 230));
        btnReset1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnReset1.setText("RESET");
        btnReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset1ActionPerformed(evt);
            }
        });

        btnClose1.setBackground(new java.awt.Color(155, 194, 230));
        btnClose1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnClose1.setText("CLOSE");
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public static void main(String args[]) {

    }
    
    private void txtVATNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVATNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVATNoActionPerformed

    private void txtRemarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRemarksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRemarksActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
//        ClearFields();
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    private void btnReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset1ActionPerformed
//        ClearFields();
    }//GEN-LAST:event_btnReset1ActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
//        this.dispose();
    }//GEN-LAST:event_btnClose1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnReset1;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JComboBox comboAccountType;
    private javax.swing.JComboBox comboBank;
    private javax.swing.JComboBox comboBranch;
    private javax.swing.JComboBox comboCategory;
    private javax.swing.JComboBox comboParent;
    private javax.swing.JComboBox comboSign;
    private javax.swing.JComboBox comboType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAccNO;
    private javax.swing.JLabel lblAccountType;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblBranch;
    private javax.swing.JLabel lblContact1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword4;
    private javax.swing.JLabel lblPassword5;
    private javax.swing.JLabel lblPassword6;
    private javax.swing.JLabel lblPassword7;
    private javax.swing.JLabel lblPhoneNo3;
    private javax.swing.JLabel lblPhoneNo4;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JLabel lblUsername3;
    private javax.swing.JLabel lblUsername4;
    private javax.swing.JLabel lblUsername6;
    private javax.swing.JLabel lblUsername7;
    private javax.swing.JLabel lblVATNo;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton radioChild;
    private javax.swing.JRadioButton radioParnt;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAccountName1;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtOpeningBalance;
    private javax.swing.JTextField txtPhoneNo1;
    private javax.swing.JTextField txtPhoneNo2;
    private javax.swing.JTextField txtRemarks;
    private javax.swing.JTextField txtVATNo;
    private javax.swing.JTextField txtcontact;
    // End of variables declaration//GEN-END:variables
}
